### ISSUE TITLE
node.publish should publish root if necessary

### ISSUE THREAD

**Issue by ReidWilliams** [IDEO-coLAB/nomad#27]
Users should be able to publish data using only node.publish without ever using node.publishRoot. publishRoot would then only be used when a user wants to explicitly restart a stream with a new root.

When user calls node.publish and there's no cache entry showing an existing stream, module should automatically call publishroot.

**Comment by gavinmcdermott** [comment]
This is now handled automatically in the `feat/pure-js` branch. Closing the issue 👍
